parameters:
  logging_level: !php/const:Monolog\Logger::INFO

services:
  logger:
    class: Monolog\Logger
    arguments:
      - 'handler'
    calls:
      - [pushHandler, ['@logging.handler']]

  logging.formatter:
    class: Monolog\Formatter\LineFormatter
    arguments:
      - '%%message%% %%context%% %%extra%%'

  logging.handler:
    class: Monolog\Handler\StreamHandler
    arguments:
      - 'php://stderr'
      - '%logging_level%'
    calls:
      - [setFormatter, ['@logging.formatter']]

# Define your own handlers and other services here
  handler.hello:
    class: Raines\Serverless\HelloHandler
    arguments:
      - '@logger'

#  handler.example:
#    class: Acme\ExampleHandler
#    arguments:
#      - '@logger'
